### ISSUE TITLE
script not parsing "me" all the time

### ISSUE THREAD

**Issue by ScrumpyJack** [HaroldPutman/hubot-encourage#1]
Sometimes I get:

>hubot encourage me
>Way to go, you!

instead of 
>Way to go, \<username\>

This is weirdly intermittent

**Comment by HaroldPutman** [comment]
if you have an extra space the regex doesn't get that "me" is you, and will say things like "Me is a great part of the team!" (expected "You is a great part of the team!" - bad grammar, but still encouraging).
Does that sound like what you are seeing?

**Comment by HaroldPutman** [comment]
On closer examination, I see that what you describe is exactly what it is designed to do. It randomly chooses between your username and the personal pronoun "you".  Because an unpredictable hubot feels more alive!

**Comment by ScrumpyJack** [comment]
Yes you are right, I see that now
